DMP-2319-Courthouse-Details-View-Users-Tab
hmcts/darts-portal pull request #1050
Opened 2024-04-26 15:58 UTC by bpires2

### Jira link (if applicable)

[DMP-2319](https://tools.hmcts.net/jira/browse/DMP-2319)

### Change description ###

- Courthouse record users page

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-05-07 14:50 UTC, DavidTMann commented
@davet1985 Is it likely to have no users against a courthouse in Prod? At the moment we just show a blank screen which confused me (on stub)

2024-05-07 15:01 UTC, davet1985 commented
> @davet1985 Is it likely to have no users against a courthouse in Prod? At the moment we just show a blank screen which confused me (on stub)

Yes, this can happen as new courthouses can be created, or all users could be removed from a courthouse.

2024-05-07 15:02 UTC, davet1985 commented
> > @davet1985 Is it likely to have no users against a courthouse in Prod? At the moment we just show a blank screen which confused me (on stub)
> 
> Yes, this can happen as new courthouses can be created, or all users could be removed from a courthouse.

Let me guess though, there's no design for what it should look like with no users?

2024-05-07 16:03 UTC, DavidTMann requested changes

2024-05-07 16:03 UTC, DavidTMann commented on src/app/core/components/common/filters/filters.component.html
> +            @if (filter.isCollapsed) {
I think isCollapsed is named incorrectly or needs to be set appropriately as currently it shows those items when expanded not collapsed

2024-05-08 14:13 UTC, DavidTMann approved these changes

2024-05-09 08:54 UTC, merged