DMP-1511 - Error - 403 - No permission at courthouse for download audio request
hmcts/darts-portal pull request #546
Opened 2023-11-15 11:44 UTC by joshw-hmcts

### Jira link (if applicable)

[DMP-1511](https://tools.hmcts.net/jira/browse/DMP-1511)

### Change description ###

Show an error screen when attempting to request audio from a courthouse that the user doesn't have permission for.

### Checklist

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2023-11-15 13:59 UTC, DavidTMann requested changes
![Screenshot 2023-11-15 at 13 48 50](https://github.com/hmcts/darts-portal/assets/17471887/9107bbd5-1124-4a79-9874-453b3f918e82)

We need to hide reporting restrictions on this screen if error occurs

Also please add functional tests in cypress request-audio-spec.cy for checking error message for audio request against that hearing

Could do with a unit test to confirm 403 is not being handled globally by ensuring navigateByUrl has not been called (similar example line 342 search component spec)

There is also a bug if you request audio for hearing 3 it shows error as expected, if you go back (don't refresh) and go to hearing 1 and request it will show same error

2023-11-16 09:35 UTC, davet1985 commented on src/app/components/hearing/hearing.component.ts
> +  private appConfigService = inject(AppConfigService);
I think this should be moved to the top with the other injected services

2023-11-16 09:39 UTC, davet1985 commented on src/app/components/hearing/hearing.component.html
> +  </ng-container>
Could this use `<app-forbidden></app-forbidden>` with the addition of a new `Input` property to override the default heading?

2023-11-16 09:43 UTC, davet1985 commented on cypress/e2e/functional/request-audio-spec.cy.js
> +    cy.get(':nth-child(2) > [scope="row"] > .govuk-checkboxes > .govuk-checkboxes__item > #\\31 ').click();
Feel free to add a `id` attribite or extra `class` to help target elements.

2023-11-16 11:52 UTC, davet1985 approved these changes

2023-11-16 11:56 UTC, merged