DMP-1614 - Annotation termplate
hmcts/darts-portal pull request #834
Opened 2024-02-20 09:20 UTC by joshw-hmcts

### Jira link (if applicable)

[DMP-1614](https://tools.hmcts.net/jira/browse/DMP-1614)

### Change description ###

### Checklist

- [X] commit messages are meaningful and follow good commit message guidelines
- [X] README and other documentation has been updated / added (if needed)
- [X] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-02-20 09:58 UTC, davet1985 requested changes
Unfortunately, the annotation document should not be accessible unless the user is signed in.

Suggest we add an endpoint to the node server, checking for authentication and returning the document.

Ideally, it would also only be accessible to users with the Judge role.

2024-02-21 16:52 UTC, davet1985 requested changes
This is better, but you can still access the file without being authenticated because assets on the node server are also public, try http://localhost:3000/assets/templates/AnnotationsTemplateExample.docx

You need to move the template outside of the assets directory.

2024-02-21 17:26 UTC, joshw-hmcts commented
> This is better, but you can still access the file without being authenticated because assets on the node server are also public, try http://localhost:3000/assets/templates/AnnotationsTemplateExample.docx
> 
> You need to move the template outside of the assets directory.

Now moved into a new "downloads" folder and path references updated

2024-02-22 09:03 UTC, davet1985 approved these changes

2024-02-22 09:22 UTC, merged